# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/degaswifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/degaswifi/proprietary/system/bin/appCoda7542Dec:system/bin/appCoda7542Dec \
    vendor/samsung/degaswifi/proprietary/system/bin/appCoda7542Enc:system/bin/appCoda7542Enc \
    vendor/samsung/degaswifi/proprietary/system/bin/atcmdsrv:system/bin/atcmdsrv \
    vendor/samsung/degaswifi/proprietary/system/bin/close_aud_path_fm.sh:system/bin/close_aud_path_fm.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/close_aud_path_hifi_headset.sh:system/bin/close_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/degaswifi/proprietary/system/bin/cp:system/bin/cp \
    vendor/samsung/degaswifi/proprietary/system/bin/cploader:system/bin/cploader \
    vendor/samsung/degaswifi/proprietary/system/bin/ddexe:system/bin/ddexe \
    vendor/samsung/degaswifi/proprietary/system/bin/diag_thp_test:system/bin/diag_thp_test \
    vendor/samsung/degaswifi/proprietary/system/bin/diag_usb_test:system/bin/diag_usb_test \
    vendor/samsung/degaswifi/proprietary/system/bin/dvfm_control.sh:system/bin/dvfm_control.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/eeh:system/bin/eeh \
    vendor/samsung/degaswifi/proprietary/system/bin/emmc_fsck:system/bin/emmc_fsck \
    vendor/samsung/degaswifi/proprietary/system/bin/exit_composite.sh:system/bin/exit_composite.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/FileMonitorService:system/bin/FileMonitorService \
    vendor/samsung/degaswifi/proprietary/system/bin/fsck.exfat:system/bin/fsck.exfat \
    vendor/samsung/degaswifi/proprietary/system/bin/hw.sh:system/bin/hw.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/hwacc:system/bin/hwacc \
    vendor/samsung/degaswifi/proprietary/system/bin/load_prod_8787.sh:system/bin/load_prod_8787.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/macloader:system/bin/macloader \
    vendor/samsung/degaswifi/proprietary/system/bin/MarvellWirelessDaemon:system/bin/MarvellWirelessDaemon \
    vendor/samsung/degaswifi/proprietary/system/bin/mlanutl:system/bin/mlanutl \
    vendor/samsung/degaswifi/proprietary/system/bin/msocket_testport:system/bin/msocket_testport \
    vendor/samsung/degaswifi/proprietary/system/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/degaswifi/proprietary/system/bin/open_aud_path_fm_headset.sh:system/bin/open_aud_path_fm_headset.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/open_aud_path_fm_speaker.sh:system/bin/open_aud_path_fm_speaker.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/open_aud_path_hifi_headset.sh:system/bin/open_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/rfkill:system/bin/rfkill \
    vendor/samsung/degaswifi/proprietary/system/bin/run_composite.sh:system/bin/run_composite.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/serial_cfun0:system/bin/serial_cfun0 \
    vendor/samsung/degaswifi/proprietary/system/bin/serial_client:system/bin/serial_client \
    vendor/samsung/degaswifi/proprietary/system/bin/setup_fs:system/bin/setup_fs \
    vendor/samsung/degaswifi/proprietary/system/bin/simal:system/bin/simal \
    vendor/samsung/degaswifi/proprietary/system/bin/smd:system/bin/smd \
    vendor/samsung/degaswifi/proprietary/system/bin/smdexe:system/bin/smdexe \
    vendor/samsung/degaswifi/proprietary/system/bin/tel_launch.sh:system/bin/tel_launch.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/tel_launch_no_gui.sh:system/bin/tel_launch_no_gui.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/telmon:system/bin/telmon \
    vendor/samsung/degaswifi/proprietary/system/bin/unload_8787.sh:system/bin/unload_8787.sh \
    vendor/samsung/degaswifi/proprietary/system/bin/vcm:system/bin/vcm \
    vendor/samsung/degaswifi/proprietary/system/bin/vt_test:system/bin/vt_test \
    vendor/samsung/degaswifi/proprietary/system/etc/bluetooth/bt_secure_manager_app_pub_key:system/etc/bluetooth/bt_secure_manager_app_pub_key \
    vendor/samsung/degaswifi/proprietary/system/etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
    vendor/samsung/degaswifi/proprietary/system/etc/bluetooth/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/bt_cal_data.conf:system/etc/firmware/mrvl/bt_cal_data.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/bt_init_cfg.conf:system/etc/firmware/mrvl/bt_init_cfg.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.bluetooth_le.xml:system/etc/permissions/android.hardware.bluetooth_le.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.camera.xml:system/etc/permissions/android.hardware.camera.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.consumerir.xml:system/etc/permissions/android.hardware.consumerir.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.wifi.direct.xml:system/etc/permissions/android.hardware.wifi.direct.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/permissions/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/ams_list.xml:system/etc/ams_list.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_basic_element.xml:system/etc/audio_basic_element.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_coeff_config.xml:system/etc/audio_coeff_config.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_gain_config.xml:system/etc/audio_gain_config.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_path_config.xml:system/etc/audio_path_config.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_swvol_calibration_def.xml:system/etc/audio_swvol_calibration_def.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_swvol_config.xml:system/etc/audio_swvol_config.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/audio_swvol_element.xml:system/etc/audio_swvol_element.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/back_camera_scene.cfg:system/etc/back_camera_scene.cfg \
    vendor/samsung/degaswifi/proprietary/system/etc/camera_profiles.xml:system/etc/camera_profiles.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/common_scene_tuning.data:system/etc/common_scene_tuning.data \
    vendor/samsung/degaswifi/proprietary/system/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/lsi3h5_still_tuning.data:system/etc/lsi3h5_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/system/etc/lsi3h5_video_tuning.data:system/etc/lsi3h5_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/system/etc/media_profiles.xml_for5640:system/etc/media_profiles.xml_for5640 \
    vendor/samsung/degaswifi/proprietary/system/etc/mrvl_agps_default.conf:system/etc/mrvl_agps_default.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/mrvl_gps_platform.conf:system/etc/mrvl_gps_platform.conf \
    vendor/samsung/degaswifi/proprietary/system/etc/MSLConfig.txt:system/etc/MSLConfig.txt \
    vendor/samsung/degaswifi/proprietary/system/etc/ov8825_still_tuning.data:system/etc/ov8825_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/system/etc/ov8825_video_tuning.data:system/etc/ov8825_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/system/etc/powerdaemon.xml:system/etc/powerdaemon.xml \
    vendor/samsung/degaswifi/proprietary/system/etc/pxa_testcfg.ini:system/etc/pxa_testcfg.ini \
    vendor/samsung/degaswifi/proprietary/system/etc/rom.bin:system/etc/rom.bin \
    vendor/samsung/degaswifi/proprietary/system/etc/sensor_config.xml:system/etc/sensor_config.xml \
    vendor/samsung/degaswifi/proprietary/system/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/degaswifi/proprietary/system/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/degaswifi/proprietary/system/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/degaswifi/proprietary/system/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/consumerir.mrvl.so:system/lib/hw/consumerir.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/degaswifi/proprietary/system/lib/soundfx/libmrvlpreprocessing.so:system/lib/soundfx/libmrvlpreprocessing.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libacm.so:system/lib/libacm.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libagps_hal.so:system/lib/libagps_hal.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libaudiodebugtool.so:system/lib/libaudiodebugtool.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libceu.so:system/lib/libceu.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcoda7542.so:system/lib/libcoda7542.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcoda7542hal.so:system/lib/libcoda7542hal.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodeccoda7542dec.so:system/lib/libcodeccoda7542dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodeccoda7542enc.so:system/lib/libcodeccoda7542enc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecpngdec.so:system/lib/libcodecpngdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libexif_jni.so:system/lib/libexif_jni.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libFileMonitorService.so:system/lib/libFileMonitorService.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libfmhal.so:system/lib/libfmhal.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libGLESv2SC.so:system/lib/libGLESv2SC.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libgputex.so:system/lib/libgputex.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libippimgp.so:system/lib/libippimgp.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libippsp.so:system/lib/libippsp.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libippvp.so:system/lib/libippvp.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libparseTim.so:system/lib/libparseTim.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libPowerSetting.so:system/lib/libPowerSetting.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libquramagifencoder.so:system/lib/libquramagifencoder.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libquramimagecodec.so:system/lib/libquramimagecodec.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/degaswifi/proprietary/system/lib/lib_SamsungRec_V03011b.so:system/lib/lib_SamsungRec_V03011b \
    vendor/samsung/degaswifi/proprietary/system/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/degaswifi/proprietary/system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libserialport.so:system/lib/libserialport.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsimal.so:system/lib/libsimal.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsmte.so:system/lib/libsmte.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libstagefright_mrvl_extractor.so:system/lib/libstagefright_mrvl_extractor.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libsthmb.so:system/lib/libsthmb.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libusbsetting.so:system/lib/libusbsetting.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libwtpsp.so:system/lib/libwtpsp.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libwtpsp_ss.so:system/lib/libwtpsp_ss.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/degaswifi/proprietary/system/lib/libxml2.so:system/lib/libxml2.so \
    vendor/samsung/degaswifi/proprietary/system/usr/idc/elan-ts.idc:system/usr/idc/elan-ts.idc \
    vendor/samsung/degaswifi/proprietary/system/usr/idc/ft5306-ts.idc:system/usr/idc/ft5306-ts.idc \
    vendor/samsung/degaswifi/proprietary/system/usr/keychars/pxa27x-keypad.kcm:system/usr/keychars/pxa27x-keypad.kcm \
    vendor/samsung/degaswifi/proprietary/system/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    vendor/samsung/degaswifi/proprietary/system/usr/keylayout/pxa27x-keypad.kl:system/usr/keylayout/pxa27x-keypad.kl \
    vendor/samsung/degaswifi/proprietary/system/usr/keylayout/Vendor_04e8_Product_7021.kl:system/usr/keylayout/Vendor_04e8_Product_7021.kl \
    vendor/samsung/degaswifi/proprietary/system/usr/lib/alsa-lib/libasound_module_ctl_codec.so:system/usr/lib/alsa-lib/libasound_module_ctl_codec.so \
    vendor/samsung/degaswifi/proprietary/system/usr/lib/alsa-lib/libasound_module_ctl_phone.so:system/usr/lib/alsa-lib/libasound_module_ctl_phone.so \
    vendor/samsung/degaswifi/proprietary/system/usr/lib/alsa-lib/libasound_module_pcm_phone.so:system/usr/lib/alsa-lib/libasound_module_pcm_phone.so \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/centor_lfe.conf:system/usr/share/alsa/pcm/centor_lfe.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
    vendor/samsung/degaswifi/proprietary/system/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/degaswifi/proprietary/system/vendor/lib/hw/lights.mrvl.so:system/vendor/lib/hw/lights.mrvl.so 
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwconfig:system/xbin/iwconfig \
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwevent:system/xbin/iwevent \
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwgetid:system/xbin/iwgetid \
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwlist:system/xbin/iwlist \
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwpriv:system/xbin/iwpriv \
    # vendor/samsung/degaswifi/proprietary/system/xbin/iwspy:system/xbin/iwspy \
    # vendor/samsung/degaswifi/proprietary/system/xbin/zip:system/xbin/zip \
    # vendor/samsung/degaswifi/proprietary/system/xbin/zipalign:system/xbin/zipalign
    # vendor/samsung/degaswifi/proprietary/system/lib/libscreenrecorder.so:system/lib/libscreenrecorder.so \
    # vendor/samsung/degaswifi/proprietary/system/bin/abcc:system/bin/abcc \
    # vendor/samsung/degaswifi/proprietary/system/bin/amixer:system/bin/amixer \
    # vendor/samsung/degaswifi/proprietary/system/bin/aplay:system/bin/aplay \
    # vendor/samsung/degaswifi/proprietary/system/bin/bootchecker:system/bin/bootchecker \
    # vendor/samsung/degaswifi/proprietary/system/bin/dttexe:system/bin/dttexe \
    # vendor/samsung/degaswifi/proprietary/system/bin/FMRadioServer:system/bin/FMRadioServer \
    # vendor/samsung/degaswifi/proprietary/system/bin/ionsyx:system/bin/ionsyx \
    # vendor/samsung/degaswifi/proprietary/system/bin/p2p_supplicant:system/bin/p2p_supplicant \
    # vendor/samsung/degaswifi/proprietary/system/bin/powerdaemon:system/bin/powerdaemon \
    # vendor/samsung/degaswifi/proprietary/system/bin/ppd_cmd:system/bin/ppd_cmd \
    # vendor/samsung/degaswifi/proprietary/system/bin/sensord:system/bin/sensord \
    # vendor/samsung/degaswifi/proprietary/system/bin/serial_client_test:system/bin/serial_client_test \
    # vendor/samsung/degaswifi/proprietary/system/bin/STUpdateTool_V4_4R:system/bin/STUpdateTool_V4_4R \
    # vendor/samsung/degaswifi/proprietary/system/bin/system_server:system/bin/system_server \
    # vendor/samsung/degaswifi/proprietary/system/bin/usr_path_ctrl:system/bin/usr_path_ctrl \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/cal_data.conf:system/etc/firmware/mrvl/cal_data.conf \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/sd8777_uapsta.bin:system/etc/firmware/mrvl/sd8777_uapsta.bin \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/SDIO8777_SDIO_SDIO.bin:system/etc/firmware/mrvl/SDIO8777_SDIO_SDIO.bin \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
    # vendor/samsung/degaswifi/proprietary/system/etc/firmware/mrvl/WlanCalData_ext.conf_0:system/etc/firmware/mrvl/WlanCalData_ext.conf_0 \
